name: Deploy Plugin Assets

on:
  push:
    branches:
      - main
    paths:
      - '.wordpress-org/**'

jobs:
  deploy-assets:
    name: Deploy Assets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy assets to WordPress.org
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: noticepulse